### PR TITLE
Upgrade terraform provider azuredevops to v1.0.1

### LINKED ISSUE #324: Upgrade terraform-provider-azuredevops to v1.0.0
Release details: https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v1.0.0

### LINKED ISSUE #329: Upgrade terraform-provider-azuredevops to v1.0.1
Release details: https://github.com/microsoft/terraform-provider-azuredevops/releases/tag/v1.0.1

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #329 
Fixes #324 

This PR performs the next major version upgrade of azuredevops. 

It removes old renames.

### CODE REVIEW

**Review by VenelinMartinov — APPROVED** [review]
Were the manual changes you made:
1. Increment major-version in .ci-mgmt
2. replace all import paths
3. remove the renames from resources.go?

**Comment by VenelinMartinov** [comment]
Also do we document the migration paths for our users? E.g. looks like they need to change the names of a bunch of resources

**Comment by iwahbe** [comment]
> Were the manual changes you made:
> 
> 1. Increment major-version in .ci-mgmt
> 2. replace all import paths
> 3. remove the renames from resources.go?

Yeah. I also set `.ci-mgmt.yaml` `VERSION_PREFIX: 3.0.0` and ran `make ci-mgmt` before reverting the `.ci-mgmt.yaml` change.

**Comment by iwahbe** [comment]
> Also do we document the migration paths for our users? E.g. looks like they need to change the names of a bunch of resources

We don't have out-of-band documentation of migration paths, but each resource changed was already depreciated at the old path.

**Pull request merged**
