### PR TITLE
Remove service connection id default

### PR DESCRIPTION
**Pull request by VenelinMartinov**
This is a targeted fix for https://github.com/pulumi/pulumi-azuredevops/issues/66 until we ship https://github.com/pulumi/pulumi-terraform-bridge/issues/1546.

I've added the upstream repo as a submodule and removed the default which causes the `RequiredWith` conflicts.

### CODE REVIEW

**Review by iwahbe — COMMENTED** [review]
The `plain -> patched` move looks perfect. 

I have the same comment as https://github.com/pulumi/pulumi-azuredevops/pull/220#pullrequestreview-1760505403 for documenting the patch.

**Comment by VenelinMartinov** [comment]
I've raised https://github.com/pulumi/pulumi-azuredevops/issues/226 for removing the patch and added a test here.

**Review by t0yv0 — APPROVED** [review]
This looks good now 🚢

**Comment by t0yv0** [comment]
Last failure is not a flake

```
Error: ../provider/resources.go:22:2: github.com/microsoft/terraform-provider-azuredevops@v0.0.0-00010101000000-000000000000 (replaced by ../upstream): reading ../upstream/go.mod: open /home/runner/work/pulumi-azuredevops/pulumi-azuredevops/upstream/go.mod: no such file or directory
```

**Comment by t0yv0** [comment]
🚢

**Pull request merged**
