### PR TITLE
Fix broken links to the documentation

### PR DESCRIPTION
**Pull request by apushnov**
Since the URLs of the documentation pages on the website were changed, need to reflect this in README as well

### CODE REVIEW

**Review by jkodroff — APPROVED** [review]
Thank you kindly!

**Comment by jkodroff** [comment]
@apushnov Can you run `make tfgen build_sdks` and re-commit? `README.md` in the repo root gets copied to the Python SDK, so this change requires a rebuild of the SDKs.

**Comment by apushnov** [comment]
Getting the following error while running the command, not sure how to eliminate it:
```
package Replatform/temp/temp/pulumi-azuredevops/bin/pulumi-tfgen-azuredevops is not in GOROOT (/usr/lib/go/src/Replatform/temp/temp/pulumi-azuredevops/bin/pulumi-tfgen-azuredevops)
malformed import path "-ldflags": leading dash
malformed import path "-X github.com/pulumi/pulumi-azuredevops/provider/v2/pkg/version.Version=2.4.0-alpha.1648761616+9b69b78b": leading dash
make: *** [Makefile:26: tfgen] Error 1

```

**Comment by guineveresaenger** [comment]
@apushnov which version of Go are you using on your machine? you shouldn't need a GOROOT. 

I also recommend a `go mod tidy`in `the `provider/` folder before running make. 

If you prefer, we can run the gen for you and push to your PR as well - let us know!

**Comment by guineveresaenger** [comment]
Fixes #97

**Comment by apushnov** [comment]
`go version go1.17.8 linux/amd64`

I go the following result when executing `go build` in the `provider` directory:

```
go build -ldflags "-X github.com/pulumi/pulumi-azuredevops/provider/v2/pkg/version.Version=2.4.0-alpha.1648761616+9b69b78b.dirty" -o /home/apushnov/git/matco/Ecomm Replatform/pulumi-azuredevops/bin/pulumi-tfgen-azuredevops  github.com/pulumi/pulumi-azuredevops/provider/v2/cmd/pulumi-tfgen-azuredevops
package Replatform/pulumi-azuredevops/bin/pulumi-tfgen-azuredevops is not in GOROOT (/usr/lib/go/src/Replatform/pulumi-azuredevops/bin/pulumi-tfgen-azuredevops)
no required module provides package github.com/pulumi/pulumi-azuredevops/provider/v2/cmd/pulumi-tfgen-azuredevops; to add it:
        go get github.com/pulumi/pulumi-azuredevops/provider/v2/cmd/pulumi-tfgen-azuredevops
```

And when trying to get the module:
```
go get github.com/pulumi/pulumi-azuredevops/provider/v2/cmd/pulumi-tfgen-azuredevops
go get: module github.com/pulumi/pulumi-azuredevops/provider@upgrade found (v0.0.0-20210412170310-6aaaddd24026), but does not contain package github.com/pulumi/pulumi-azuredevops/provider/v2/cmd/pulumi-tfgen-azuredevops
```
Not sure what's wrong here.

**Pull request closed without merging**
